"""Prototype sentences for semantic section relevance scoring."""

from __future__ import annotations

DRUG_SECTION_PROTOTYPES: dict[str, list[str]] = {
    "INDICATIONS AND USAGE": [
        "Indications and usage for this drug in heart failure or related conditions.",
        "Approved therapeutic indications and labeled uses.",
        "This medication is indicated for the treatment of heart failure with reduced ejection fraction.",
        "Clinical indications include HFrEF, HFpEF, and related cardiovascular conditions.",
        "The drug is approved for use in patients with symptomatic heart failure.",
    ],
    "DOSAGE AND ADMINISTRATION": [
        "Recommended starting dose, titration, and administration instructions.",
        "Dosing adjustments for renal impairment or special populations.",
        "Initial dose, titration schedule, and maximum recommended dose.",
        "Take this medication orally once or twice daily as directed.",
        "Dose may be adjusted based on clinical response and tolerability.",
    ],
    "CONTRAINDICATIONS": [
        "This drug is contraindicated in patients with specific conditions.",
        "Do not use in patients who have hypersensitivity or absolute contraindications.",
        "Contraindicated in patients with history of angioedema or anaphylaxis.",
        "Not recommended for patients with severe hepatic impairment.",
        "Avoid use in pregnancy unless benefits outweigh risks.",
    ],
    "WARNINGS AND PRECAUTIONS": [
        "Warnings and precautions including boxed warnings and serious risks.",
        "Monitor patients for hypotension, hyperkalemia, or renal dysfunction.",
        "Boxed warning for fetal toxicity and risk of serious adverse events.",
        "May cause hypotension, especially in volume-depleted patients.",
        "Regular monitoring of renal function and electrolytes is recommended.",
    ],
    "ADVERSE REACTIONS": [
        "Common and serious adverse reactions observed in clinical trials.",
        "Most common adverse reactions include dizziness, hypotension, and hyperkalemia.",
        "Clinical trials reported adverse reactions in greater than 5% of patients.",
        "Serious adverse reactions may include angioedema and renal dysfunction.",
        "Post-marketing experience includes reports of hepatic injury.",
    ],
    "DRUG INTERACTIONS": [
        "Drug-drug interactions with concomitant medications and CYP inhibitors.",
        "Concomitant use with ACE inhibitors may increase risk of hyperkalemia.",
        "May potentiate hypotensive effects when combined with other antihypertensives.",
        "Avoid concomitant use with potassium-sparing diuretics.",
        "Check for interactions with NSAIDs, lithium, and anticoagulants.",
    ],
    "USE IN SPECIFIC POPULATIONS": [
        "Use in pregnancy, lactation, pediatrics, geriatrics, and renal impairment.",
        "Safety and effectiveness in pediatric patients have not been established.",
        "Use with caution in elderly patients due to increased sensitivity.",
        "Not recommended during pregnancy unless clearly needed.",
        "Discontinue breastfeeding when using this medication.",
    ],
    "RENAL IMPAIRMENT": [
        "Dose modification or contraindication in renal impairment based on eGFR.",
        "Reduce dose or avoid use in patients with severe renal impairment.",
        "Monitor renal function closely in patients with eGFR below 60 mL/min.",
        "No dose adjustment needed for mild to moderate renal impairment.",
        "Use is contraindicated in patients with anuria or severe renal dysfunction.",
    ],
    # NEW SECTIONS
    "CLINICAL PHARMACOLOGY": [
        "Mechanism of action, pharmacodynamics, and pharmacokinetics of this drug.",
        "How this medication works at the molecular and cellular level.",
        "The drug inhibits neprilysin and blocks the angiotensin II receptor.",
        "Pharmacokinetic properties including half-life, bioavailability, and metabolism.",
        "Peak plasma concentration reached within 2-4 hours of oral administration.",
    ],
    "CLINICAL STUDIES": [
        "Results from randomized controlled trials and clinical studies.",
        "Efficacy and safety data from pivotal clinical trials.",
        "The landmark trial demonstrated a 20% reduction in cardiovascular death.",
        "Clinical studies enrolled over 8,000 patients with heart failure.",
        "Subgroup analyses showed consistent benefit across NYHA functional classes.",
    ],
    "OVERDOSAGE": [
        "Signs and symptoms of overdose and recommended management.",
        "Toxic doses, antidotes, and emergency treatment for overdose.",
        "In case of overdose, discontinue therapy and initiate supportive care.",
        "There is no specific antidote for this medication overdose.",
        "Hemodialysis may be considered for severe overdose cases.",
    ],
    "DESCRIPTION": [
        "Chemical description and formulation of the drug product.",
        "Active ingredients and excipients in the drug formulation.",
        "The drug is available as oral tablets in various strengths.",
        "Chemical name, molecular weight, and structural formula.",
        "Store at room temperature away from moisture and heat.",
    ],
    "BLACK BOX WARNING": [
        "Boxed warning for serious or life-threatening adverse reactions.",
        "Fetal toxicity warning - contraindicated in pregnancy.",
        "Risk of angioedema and anaphylaxis requiring immediate intervention.",
        "Black box warning for increased mortality in certain patient populations.",
        "Serious warnings about hepatic toxicity and renal failure.",
    ],
    "PATIENT COUNSELING": [
        "Information for patients about drug administration and side effects.",
        "Counsel patients on importance of adherence and monitoring.",
        "Instruct patients to report signs of hypotension or hyperkalemia.",
        "Advise patients to avoid potassium supplements and salt substitutes.",
        "Inform patients about potential dizziness and avoid driving if affected.",
    ],
    "HOW SUPPLIED": [
        "Available dosage forms, strengths, and packaging information.",
        "Tablets available in 25 mg, 50 mg, and 100 mg strengths.",
        "Store at 20-25°C (68-77°F) with excursions permitted.",
        "Bottles of 30 or 90 tablets with child-resistant closures.",
        "Keep out of reach of children and pets.",
    ],
    "GERIATRIC USE": [
        "Use in elderly patients requires careful dose titration.",
        "No overall differences in safety observed in clinical trials.",
        "Monitor renal function and blood pressure in older adults.",
        "Increased sensitivity to hypotensive effects in elderly.",
        "Start at low end of dosing range in patients over 75 years.",
    ],
    "PEDIATRIC USE": [
        "Safety and effectiveness not established in pediatric patients.",
        "No pediatric-specific dosing recommendations available.",
        "Use only if potential benefit justifies potential risk.",
        "Not recommended for children under 18 years of age.",
        "Clinical trials in pediatric heart failure are ongoing.",
    ],
    "PREGNANCY": [
        "Contraindicated in pregnancy due to fetal toxicity risk.",
        "Category X - should not be used during pregnancy.",
        "Discontinue immediately if pregnancy is suspected.",
        "May cause fetal harm when administered to pregnant women.",
        "Pregnancy testing recommended before initiating therapy.",
    ],
    "NURSING MOTHERS": [
        "Not recommended for breastfeeding mothers.",
        "Drug is excreted in human milk.",
        "Discontinue breastfeeding or discontinue the drug.",
        "Consider pumping and discarding breast milk during treatment.",
        "Infant exposure through breast milk may cause adverse effects.",
    ],
    "TOXICOLOGY": [
        "Nonclinical toxicity studies and carcinogenicity data.",
        "No evidence of mutagenicity or clastogenicity in animal studies.",
        "Impairment of fertility observed in animal studies at high doses.",
        "No teratogenic effects observed in reproductive toxicology studies.",
        "Long-term carcinogenicity studies in rodents were negative.",
    ],
}

GUIDELINE_TOPIC_PROTOTYPES: dict[str, list[str]] = {
    "recommendations": [
        "Clinical practice recommendation with class of recommendation and level of evidence.",
        "We recommend initiating guideline-directed medical therapy.",
        "Class I recommendation for ACE inhibitors in HFrEF.",
        "Strong recommendation based on high-quality evidence from RCTs.",
        "Guideline recommendation for comprehensive heart failure management.",
    ],
    "drug therapy": [
        "Pharmacologic treatment options including ACE inhibitors, beta blockers, and SGLT2 inhibitors.",
        "Initiation and optimization of heart failure drug therapy.",
        "GDMT includes evidence-based medications that improve outcomes.",
        "Multiple drug classes recommended for symptomatic HF management.",
        "Consider adding SGLT2 inhibitors to standard heart failure therapy.",
    ],
    "dosing": [
        "Starting dose, titration schedule, and target doses for heart failure medications.",
        "Dose adjustment based on blood pressure, heart rate, or renal function.",
        "Start at low dose and titrate to evidence-based target doses.",
        "Maximum tolerated dose should be achieved for optimal benefit.",
        "Dose reductions may be needed for hypotension or renal dysfunction.",
    ],
    "monitoring": [
        "Laboratory monitoring of eGFR, electrolytes, and potassium during therapy.",
        "Safety follow-up after initiating or titrating guideline-directed medical therapy.",
        "Monitor renal function and electrolytes within 1-2 weeks of initiation.",
        "Regular monitoring of blood pressure and heart rate recommended.",
        "Periodic assessment of volume status and symptom improvement.",
    ],
    "drug interactions": [
        "Clinically important drug-drug interactions with concomitant heart failure therapies.",
        "Avoid co-administration of interacting medications that increase adverse risk.",
        "Check for interactions with NSAIDs, antiarrhythmics, and CYP substrates.",
        "ACE inhibitors and ARBs should not be used together.",
        "SGLT2 inhibitors may interact with insulin and secretagogues.",
    ],
    "warnings": [
        "Boxed warnings, precautions, and serious treatment-related risks.",
        "Clinicians should be aware of black-box warnings and high-risk adverse effects.",
        "Warnings about angioedema, hypotension, and renal dysfunction.",
        "Fetal toxicity warning requires pregnancy prevention strategies.",
        "Monitor for signs of hepatic injury and discontinue if needed.",
    ],
    "contraindications": [
        "Treatment is contraindicated in patients with specific comorbidities.",
        "Contraindicated in pregnancy, lactation, and severe renal impairment.",
        "Do not use in patients with history of angioedema to ACE inhibitors.",
        "Avoid in patients with bilateral renal artery stenosis.",
        "Contraindicated in patients with hypersensitivity to the drug.",
        "Do not use concomitant ACE inhibitors and ARBs together - contraindicated.",
        "Contraindicated in pregnancy due to teratogenic risk.",
        "Do not use in patients with hereditary galactose intolerance.",
        "Avoid use in patients with severe hepatic impairment.",
        "Contraindicated in patients with history of drug-induced angioedema.",
    ],
    "comorbidities": [
        "Management of comorbid conditions such as diabetes, CKD, or atrial fibrillation.",
        "Optimize management of comorbidities to improve HF outcomes.",
        "Consider drug interactions with common comorbidities.",
        "Screen for and treat sleep apnea in HF patients.",
        "Manage depression and cognitive impairment in chronic HF.",
    ],
    "renal dysfunction": [
        "Therapy adjustments when eGFR declines or chronic kidney disease is present.",
        "Dosing considerations in renal impairment and hepatic impairment.",
        "Reduce dose or avoid ACE inhibitors when eGFR is below 30.",
        "Monitor renal function closely in CKD patients.",
        "Dialysis patients may require dose adjustments.",
    ],
    "hyperkalemia": [
        "Serum potassium thresholds and hyperkalemia risk with RAAS inhibitors or MRA.",
        "Avoid potassium supplements and monitor potassium regularly.",
        "Hold medication if potassium exceeds 5.5 mEq/L.",
        "Risk of life-threatening hyperkalemia with combined RAAS blockade.",
        "Educate patients on dietary potassium restriction.",
    ],
    "atrial fibrillation": [
        "Anticoagulation and rate control in heart failure with atrial fibrillation.",
        "Consider rhythm control strategies in HFpEF with AF.",
        "AF may worsen HF symptoms and increase hospitalization risk.",
        "Rate control with beta blockers or digoxin recommended.",
        "Anticoagulation based on CHA2DS2-VASc score.",
    ],
    "diabetes": [
        "Glycemic management and SGLT2 inhibitor use in patients with diabetes.",
        "SGLT2 inhibitors provide cardiovascular benefit in diabetic HF patients.",
        "Monitor blood glucose and adjust hypoglycemic agents as needed.",
        "Avoid empagliflozin in type 1 diabetes or DKA.",
        "Consider SGLT2 inhibitors even in pre-diabetes.",
    ],
    "hypertension": [
        "Blood pressure targets and antihypertensive therapy in heart failure.",
        "Target BP below 130/80 mmHg in HF patients.",
        "ACE inhibitors and ARBs help control BP and improve outcomes.",
        "Avoid abrupt discontinuation of antihypertensives.",
        "Consider volume status when treating hypertension in HF.",
    ],
    # NEW TOPICS
    "heart failure phenotypes": [
        "HFrEF with reduced ejection fraction less than 40%.",
        "HFpEF with preserved ejection fraction greater than 50%.",
        "HFmrEF with mid-range ejection fraction 40-49%.",
        "Phenotype-specific treatment strategies recommended.",
        "LVEF assessment guides therapeutic decision-making.",
    ],
    "biomarkers": [
        "BNP and NT-proBNP as diagnostic and prognostic biomarkers in heart failure.",
        "Elevated natriuretic peptides indicate worse outcomes in HF patients.",
        "Serial BNP measurements guide therapy optimization and risk stratification.",
        "NT-proBNP target of less than 1000 pg/mL associated with improved outcomes.",
        "Biomarker-guided therapy reduces heart failure hospitalizations.",
    ],
    "liver function": [
        "Abnormal liver function tests in heart failure patients with congestion.",
        "Hepatic dysfunction secondary to right heart failure and venous congestion.",
        "Monitor LFTs in patients on hepatotoxic medications.",
        "Transaminase elevation may require dose adjustment or discontinuation.",
        "Fulminant hepatic failure is a rare but serious complication.",
    ],
    "electrolyte abnormalities": [
        "Hyponatremia is associated with poor prognosis in acute HF.",
        "Hypokalemia increases risk of arrhythmias in HF patients.",
        "Monitor magnesium levels in patients on diuretics.",
        "Correct electrolyte imbalances before initiating GDMT.",
        "Sodium levels guide diuretic therapy and fluid management.",
    ],
    "volume status": [
        "Volume overload and congestion are primary causes of HF hospitalization.",
        "Physical exam findings include elevated JVP, rales, and edema.",
        "Daily weight monitoring helps detect fluid accumulation.",
        "Diuretics are first-line for volume management.",
        "Consider ultrafiltration in diuretic-resistant patients.",
    ],
    "device therapy": [
        "ICD is indicated for primary prevention of sudden cardiac death.",
        "CRT improves outcomes in patients with wide QRS and reduced EF.",
        "Consider LVAD as bridge to transplant or destination therapy.",
        "Device therapy should be optimized alongside GDMT.",
        "Regular device interrogation and optimization recommended.",
    ],
    "acute decompensation": [
        "Acute decompensated heart failure requires urgent diuresis.",
        "Intravenous loop diuretics are first-line for acute HF.",
        "Nesiritide and other vasodilators may be used in acute setting.",
        "Identify and treat precipitating factors.",
        "Consider inotropic support in cardiogenic shock.",
    ],
    "quality of life": [
        "Heart failure significantly impacts quality of life and functional status.",
        "Six-minute walk test assesses functional capacity.",
        "Patient-reported outcomes should guide treatment decisions.",
        "Cardiac rehabilitation improves symptoms and exercise tolerance.",
        "Palliative care should be integrated for advanced HF.",
    ],
    "hospitalization": [
        "HF hospitalization is associated with poor prognosis.",
        "Post-discharge follow-up reduces readmission rates.",
        "Identify high-risk patients for intensive management.",
        "Medication reconciliation is critical at discharge.",
        "Heart failure readmission is a quality measure.",
    ],
    "mortality": [
        "HF has prognosis worse than many cancers with 50% five-year mortality.",
        "Cardiovascular death is the leading cause of mortality in HF.",
        "Sudden cardiac death accounts for significant mortality.",
        "GDMT reduces all-cause and cardiovascular mortality.",
        "Risk stratification helps identify high-risk patients.",
    ],
    "guideline adherence": [
        "Guideline-directed medical therapy improves survival.",
        "Adherence to GDMT is associated with better outcomes.",
        "Only one-third of HF patients receive optimal GDMT.",
        "Quality improvement initiatives increase GDMT utilization.",
        "Multidisciplinary teams improve guideline adherence.",
    ],
    "special populations": [
        "Elderly patients require careful dose titration and monitoring.",
        "Pediatric HF has unique etiologies and treatment approaches.",
        "Pregnancy requires careful risk-benefit assessment.",
        "Renal and hepatic impairment require dose adjustments.",
        "Frailty should be assessed in older HF patients.",
    ],
    "medication adherence": [
        "Medication non-adherence is a common cause of HF exacerbation.",
        "Simplify regimens to improve adherence.",
        "Monitor medication possession ratio for adherence assessment.",
        "Education and follow-up improve medication persistence.",
        "Address cost barriers to improve adherence.",
    ],
    "race and ethnicity": [
        "African American patients may respond differently to certain therapies.",
        "Health disparities affect HF outcomes in minority populations.",
        "Consider socioeconomic factors in treatment planning.",
        "Culturally tailored education improves outcomes.",
        "Race-specific data may inform treatment decisions.",
    ],
    "clinical_numbers": [
        "eGFR thresholds for dose adjustment such as eGFR below 30 mL/min.",
        "Serum potassium cutoff above 5.0 or 5.5 mEq/L for safety monitoring.",
        "Left ventricular ejection fraction less than 35 percent.",
        "BNP or NT-proBNP target levels for diagnosis and monitoring.",
        "NYHA functional classification from Class I to Class IV.",
        "Blood pressure targets below 130/80 mmHg for HF patients.",
        "Heart rate targets between 50-60 bpm for beta blocker therapy.",
        "Serum creatinine and eGFR cutoffs for renal dose adjustment.",
    ],
}
