EXPLANATION_MODEL = "qwen2.5:7b"
VERIFICATION_MODEL = "qwen2.5:1.5b"
EMBEDDING_PROVIDER = "ollama"
EMBEDDING_MODEL = "bge-m3"
EMBEDDING_TOKENIZER = "BAAI/bge-m3"
EMBEDDING_DIMENSIONS = 1024
CHROMA_COLLECTION = "heart_failure_evidence"
CHROMA_INDEX_VERSION = "heart_failure_chunks_v3"
